2024-09-17 18:54:03,189 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Current SDK version is 0.18.0
2024-09-17 18:54:03,189 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Configure stats pid to 41788
2024-09-17 18:54:03,189 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Loading settings from C:\Users\aaron.l\.config\wandb\settings
2024-09-17 18:54:03,189 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Loading settings from C:\Users\aaron.l\Documents\LighteningSegmentation\wandb\settings
2024-09-17 18:54:03,189 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-17 18:54:03,189 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'C:\\Users\\aaron.l\\Documents\\LighteningSegmentation\\main.py', 'program': '.\\main.py'}
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_init.py:_log_setup():525] Logging user logs to .\wandb\run-20240917_185403-90rdhzsd\logs\debug.log
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_init.py:_log_setup():526] Logging internal logs to .\wandb\run-20240917_185403-90rdhzsd\logs\debug-internal.log
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_init.py:init():609] calling init triggers
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_init.py:init():616] wandb.init called with sweep_config: {}
config: {}
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_init.py:init():659] starting backend
2024-09-17 18:54:03,209 INFO    MainThread:41788 [wandb_init.py:init():663] setting up manager
2024-09-17 18:54:03,210 INFO    MainThread:41788 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-09-17 18:54:03,213 INFO    MainThread:41788 [wandb_init.py:init():671] backend started and connected
2024-09-17 18:54:03,218 INFO    MainThread:41788 [wandb_init.py:init():766] updated telemetry
2024-09-17 18:54:03,237 INFO    MainThread:41788 [wandb_init.py:init():799] communicating run to backend with 90.0 second timeout
2024-09-17 18:54:03,329 ERROR   MainThread:41788 [wandb_init.py:init():825] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity Zisheng Luo not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-17 18:54:03,329 ERROR   MainThread:41788 [wandb_init.py:init():1244] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\aaron.l\miniconda3\envs\seg\lib\site-packages\wandb\sdk\wandb_init.py", line 1234, in init
    return wi.init()
  File "C:\Users\aaron.l\miniconda3\envs\seg\lib\site-packages\wandb\sdk\wandb_init.py", line 831, in init
    raise error
wandb.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity Zisheng Luo not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-17 18:54:03,552 WARNING MsgRouterThr:41788 [router.py:message_loop():77] message_loop has been closed
