2024-09-17 18:55:52,350 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Current SDK version is 0.18.0
2024-09-17 18:55:52,350 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Configure stats pid to 7740
2024-09-17 18:55:52,350 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Loading settings from C:\Users\aaron.l\.config\wandb\settings
2024-09-17 18:55:52,350 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Loading settings from C:\Users\aaron.l\Documents\LighteningSegmentation\wandb\settings
2024-09-17 18:55:52,350 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-17 18:55:52,350 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-17 18:55:52,366 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'C:\\Users\\aaron.l\\Documents\\LighteningSegmentation\\main.py', 'program': '.\\main.py'}
2024-09-17 18:55:52,366 INFO    MainThread:7740 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-17 18:55:52,366 INFO    MainThread:7740 [wandb_init.py:_log_setup():525] Logging user logs to .\wandb\run-20240917_185552-gd28amwy\logs\debug.log
2024-09-17 18:55:52,367 INFO    MainThread:7740 [wandb_init.py:_log_setup():526] Logging internal logs to .\wandb\run-20240917_185552-gd28amwy\logs\debug-internal.log
2024-09-17 18:55:52,367 INFO    MainThread:7740 [wandb_init.py:init():609] calling init triggers
2024-09-17 18:55:52,367 INFO    MainThread:7740 [wandb_init.py:init():616] wandb.init called with sweep_config: {}
config: {}
2024-09-17 18:55:52,367 INFO    MainThread:7740 [wandb_init.py:init():659] starting backend
2024-09-17 18:55:52,367 INFO    MainThread:7740 [wandb_init.py:init():663] setting up manager
2024-09-17 18:55:52,367 INFO    MainThread:7740 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-09-17 18:55:52,371 INFO    MainThread:7740 [wandb_init.py:init():671] backend started and connected
2024-09-17 18:55:52,376 INFO    MainThread:7740 [wandb_init.py:init():766] updated telemetry
2024-09-17 18:55:52,393 INFO    MainThread:7740 [wandb_init.py:init():799] communicating run to backend with 90.0 second timeout
2024-09-17 18:55:52,502 ERROR   MainThread:7740 [wandb_init.py:init():825] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-09-17 18:55:52,502 ERROR   MainThread:7740 [wandb_init.py:init():1244] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\aaron.l\miniconda3\envs\seg\lib\site-packages\wandb\sdk\wandb_init.py", line 1234, in init
    return wi.init()
  File "C:\Users\aaron.l\miniconda3\envs\seg\lib\site-packages\wandb\sdk\wandb_init.py", line 831, in init
    raise error
wandb.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-09-17 18:55:52,676 WARNING MsgRouterThr:7740 [router.py:message_loop():77] message_loop has been closed
